# Generated by Django 3.2.3 on 2021-05-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchreports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('guild_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'guilds',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Guilds',
        ),
    ]
