# Generated by Django 3.2.5 on 2021-09-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchreports', '0002_auto_20210718_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='guild_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='deck',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
