# Generated by Django 2.2.22 on 2021-05-23 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtext', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uuid', models.UUIDField(unique=True)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super Rare')], max_length=2)),
                ('cardnum', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.Card')),
            ],
        ),
        migrations.CreateModel(
            name='CharCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction', models.CharField(choices=[('AB', 'Autobot'), ('DC', 'Decepticon'), ('MR', 'Mercenary')], max_length=2)),
                ('subtitle', models.CharField(max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Pip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('O', 'Orange'), ('U', 'Blue'), ('B', 'Black'), ('W', 'White'), ('G', 'Green')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StratCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('cardtext', models.CharField(max_length=1000)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.Card')),
                ('charcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.CharCard')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200)),
                ('cards', models.ManyToManyField(through='carddb.CardSet', to='carddb.Card')),
            ],
        ),
        migrations.CreateModel(
            name='PipSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.BattleCard')),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.Pip')),
            ],
        ),
        migrations.AddField(
            model_name='pip',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.Trait'),
        ),
        migrations.CreateModel(
            name='CharSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ALT', 'Alt Mode'), ('BOT', 'Bot Mode'), ('BODY', 'Body Mode'), ('HEAD', 'Head Mode'), ('LEGD', 'Legend Mode'), ('COMB', 'Combiner Mode'), ('UPGR', 'Upgrade Mode')], max_length=4)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('health', models.IntegerField()),
                ('cardtext', models.CharField(max_length=1000)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.CharCard')),
                ('traits', models.ManyToManyField(to='carddb.Trait')),
            ],
        ),
        migrations.AddField(
            model_name='cardset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.Set'),
        ),
        migrations.CreateModel(
            name='BCardSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.BCardType')),
            ],
        ),
        migrations.AddField(
            model_name='battlecard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.Card'),
        ),
        migrations.AddField(
            model_name='battlecard',
            name='subtype',
            field=models.ManyToManyField(to='carddb.BCardSubtype'),
        ),
        migrations.AddField(
            model_name='battlecard',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.BCardType'),
        ),
    ]
