# Generated by Django 2.2.22 on 2021-05-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carddb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlecard',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carddb.Card'),
        ),
        migrations.AlterField(
            model_name='charcard',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carddb.Card'),
        ),
        migrations.AlterField(
            model_name='stratcard',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carddb.Card'),
        ),
    ]
