# Generated by Django 2.2.22 on 2021-05-23 00:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carddb', '0002_auto_20210523_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardset',
            name='card_uuid',
        ),
        migrations.AlterField(
            model_name='cardset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
