# Generated by Django 2.2.22 on 2021-05-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carddb', '0003_auto_20210523_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charcard',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='battlecard',
            name='faction',
            field=models.CharField(choices=[('AB', 'Autobot'), ('DC', 'Decepticon'), ('MR', 'Mercenary')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
