# Generated by Django 2.2.22 on 2021-05-23 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carddb', '0004_auto_20210523_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcardsubtype',
            options={'verbose_name': 'Battle Card Subtype'},
        ),
        migrations.AlterModelOptions(
            name='bcardtype',
            options={'verbose_name': 'Battle Card Type'},
        ),
        migrations.AlterModelOptions(
            name='charcard',
            options={'verbose_name': 'Character'},
        ),
        migrations.AlterModelOptions(
            name='charside',
            options={'verbose_name': 'Character Mode'},
        ),
        migrations.AlterModelOptions(
            name='stratcard',
            options={'verbose_name': 'Stratagem'},
        ),
        migrations.AlterField(
            model_name='battlecard',
            name='cardtext',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='battlecard',
            name='faction',
            field=models.CharField(blank=True, choices=[('AB', 'Autobot'), ('DC', 'Decepticon'), ('MR', 'Mercenary')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='battlecard',
            name='subtype',
            field=models.ManyToManyField(blank=True, to='carddb.BCardSubtype'),
        ),
        migrations.AlterField(
            model_name='bcardsubtype',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='carddb.BCardType'),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stratcard',
            name='cardtext',
            field=models.TextField(max_length=4000),
        ),
    ]
