# Generated by Django 2.2.22 on 2021-05-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carddb', '0005_auto_20210523_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charside',
            name='cardtext',
            field=models.TextField(max_length=4000),
        ),
    ]
