# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-alpine

WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFER 1

COPY ./requirements.txt .

RUN apk update \
    && apk add --virtual build-deps python3-dev gcc musl-dev \
    && apk add --no-cache mariadb-dev \
    && pip install --upgrade pip \
    && pip install --no-cache -r requirements.txt \
    && apk del build-deps

COPY . .